### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by LuckyMo-it** [Raunaksplanet/My-CS-Store#5]
upload college dsa questions

**Comment by Raunaksplanet** [comment]
Sure

**Comment by LuckyMo-it** [comment]
should i learn new things or should focus on foundation in summer holiday  as 3sem student  of decolian

**Comment by Raunaksplanet** [comment]
Being honest with you on 1st and 2nd half year of college focus on basics and foundation, Then go for unique thing you like to do. It can be anything like  development, CyberSec, backend dev etc
